---

# AFS cell name
afs_cell: example.com

# cell organization name
afs_desc: Example

# kerberos realm
afs_realm: EXAMPLE.COM

# afs mountpoint
afs_mountpoint: /afs

# Path to locally generated files.
afs_local_dir: "{{ '~/.ansible-openafs' | expanduser }}/{{ afs_cell }}"

# openafs yum repo for client packages
afs_openafs_client_repourl: https://download.sinenomine.net/openafs/bins/1.8.2/el7/$basearch

# Installation method.
# One of: 'package-manager', 'rsync'
afs_client_install_method: package-manager

# Install kernel module with DKMS
afs_client_install_dkms: no

# Build options for rsync install method.
afs_client_build_force: no
afs_client_build_builddir: "/usr/local/src/openafs_client"
afs_client_build_destdir: "/tmp/openafs_client"
afs_client_build_fetch_method: "git"
afs_client_build_git_repo: "https://github.com/openafs/openafs"
afs_client_build_git_ref: "master"

# openafs kmod package release prefix
afs_openafs_kmod_prefix: 1

# afs filesystem mount point
afs_cacheinfo_mount: "{{ afs_mountpoint }}"

# afs cache mount point
afs_cacheinfo_cache: /usr/vice/cache

# afs cache size
# TODO: create partition or autodecte
afs_cacheinfo_size: 50000

# afsd options
afs_afsd_opts: -dynroot -fakestat -afsdb
