---
afs_devel_user: "{{ lookup('env', 'USER') }}"

afs_devel_topdir: "/home/{{ afs_devel_user }}/openafs"

afs_devel_builddir: "/usr/local/src/openafs"

afs_devel_build_server: yes

afs_devel_build_client: yes

afs_devel_destdir: "/tmp/openafs"

afs_devel_fetch_method: "git"

afs_devel_git_repo: "https://github.com/openafs/openafs"

afs_devel_git_ref: "master"

afs_devel_make_jobs: "{{ ansible_facts.processor_vcpus }}"
