---
- name: Gather variables for each operating system
  include_vars: "{{ ansible_os_family|lower }}.yaml"

- name: Make local directory
  run_once: true
  delegate_to: localhost
  become: no
  file:
    path: "{{ afs_local_dir }}"
    state: directory
    mode: 0755

- name: Generate cell configuration files
  run_once: true
  delegate_to: localhost
  become: no
  template:
    src: "{{ item }}.j2"
    dest: "{{ afs_local_dir }}/{{ item }}"
  with_items:
    - CellServDB
    - ThisCell
    - UserList

- name: Create the Kerberos service key
  command: >
    {{ afs_kadmin }}
    -w {{ afs_admin_password }}
    -p {{ afs_admin_principal }}@{{ afs_realm }}
    -r "{{ afs_realm }}"
    -q "add_principal -randkey afs/{{ afs_cell }}@{{ afs_realm }}"
  register: kadmin_results
  changed_when: >
    kadmin_results.rc == 0
    and not "already exists while creating" in kadmin_results.stderr
  when: inventory_hostname == ansible_play_hosts[0]

- include_tasks: "system-{{ afs_firewall }}.yaml"
  when: afs_firewall is defined

- name: Setup SELinux mode
  selinux:
    state: "{{ afs_selinux_mode }}"
    policy: targeted
  when: afs_selinux|bool and afs_selinux_mode in ['disabled','enforcing','permissive']

- name: Setup SELinux policies
  include_tasks: selinux-policies.yaml
  when: afs_selinux|bool and afs_selinux_mode != 'disabled'

- include_tasks: server-partitions.yaml

- include_tasks: "install-{{ ansible_pkg_mgr }}.yaml"
  when: afs_server_install_method == 'package-manager'

- include_tasks: "install-{{ afs_server_install_method }}.yaml"
  when: afs_server_install_method != 'package-manager'

- include_tasks: server-config.yaml

- include_tasks: server-key.yaml

- include_tasks: selinux-contexts.yaml
  when: afs_selinux|bool and afs_selinux_mode != 'disabled'

- name: Start the OpenAFS servers
  service:
    name: "{{ afs_server_service }}"
    state: started
    enabled: yes
  register: afs_server_service_result

- include_tasks: cell-bootstrap.yaml
  when: inventory_hostname == ansible_play_hosts[0]
